In [1]:
import pandas as pd

/gpfs/fs1/home/m/moh22/moh22/.virtualenvs/jupyternotebook/lib/python3.8/site-packages/pandas/core/computation/expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [2]:
def merge_CSV(files, output):
    data = []
    for file in files:
        data.append(pd.read_csv(file))
    # Concatenate the dataframes vertically
    merge = pd.concat(data, axis=0)
    # Save the concatenated dataframe to the output file
    merge.to_csv(output, sep=',', index=False)

# List of specific CSV files to be combined
file_names = [
    'output_dist_res_2rcq_apo.csv',
    'output_dist_res_2rct_rtol.csv',
    'output_dist_res_7k3i_2lg.csv'
]

# Merge the listed files into a single combined_output.csv
merge_CSV(file_names, 'output_dist_res_merged.csv')

In [3]:
df = pd.read_csv('output_dist_res_merged.csv')
df

,res5.6,res5.7,res5.8,res5.9,res5.10,res5.11,res5.12,res5.13,res5.14,res5.15,...,res128.129,res128.130,res128.131,res128.132,res129.130,res129.131,res129.132,res130.131,res130.132,res131.132
0,5.407337,10.482441,8.469459,17.673695,19.133048,18.797942,21.819081,22.812309,25.495230,28.934740,...,8.226906,6.112077,13.782994,16.866103,6.670267,8.126890,12.585761,9.774247,10.844019,8.766173
1,4.955437,10.028155,8.201441,17.257158,18.994018,18.581755,21.714995,23.158845,26.878762,29.516173,...,8.270698,6.027291,13.355211,16.573107,7.241767,8.863592,12.935445,9.205965,10.648681,8.250715
2,4.960468,9.960084,8.275219,17.353984,19.483063,18.532192,21.928563,23.131635,26.381742,29.300909,...,8.113461,5.766623,13.407373,16.350316,6.934718,8.009755,12.639241,9.428502,10.665795,8.434454
3,5.379959,10.336671,8.879415,17.396712,19.484406,19.048587,22.128602,23.161370,25.704514,29.661989,...,7.901107,5.591941,13.315268,15.850088,7.036024,9.055805,12.687386,9.375483,10.333548,8.345388
4,5.464529,10.103715,8.908808,17.755440,19.297482,19.633335,22.901518,23.418241,25.947997,29.792326,...,8.135606,5.936077,13.172597,16.812558,7.093227,8.744347,13.425316,8.995312,10.931019,8.577032
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,5.483158,10.329985,8.564280,17.435285,19.301368,19.138433,22.289809,23.022353,25.376892,29.015323,...,8.133984,5.497425,13.157076,17.287069,7.028162,8.579109,12.747297,9.288772,12.071921,9.268860
29996,5.299619,10.320407,8.055226,17.323371,19.343470,18.701883,22.025867,22.593965,26.832757,29.574867,...,8.087629,5.601638,13.344286,17.254815,6.819330,8.264103,12.724879,9.250247,11.897912,8.958594
29997,5.700559,10.704886,8.254407,17.685267,19.689112,19.383601,23.267435,23.883562,25.847588,29.798946,...,8.153757,5.547323,13.398244,17.110465,7.016802,8.415601,13.076055,9.500828,11.714073,9.131217
29998,5.466406,10.060318,8.691018,17.401650,19.485097,19.246568,23.243095,23.228704,25.802164,29.120280,...,8.275004,6.017774,14.351773,18.244911,6.609309,8.806381,13.371229,9.483417,12.408144,8.320410
29999,5.571569,10.729368,8.217039,17.220870,19.848215,18.847415,23.549201,23.393714,25.697255,29.185487,...,8.281221,5.763569,13.288101,17.630195,6.995748,8.204958,12.947467,9.051264,12.136627,9.078994

In [4]:
df.drop('Unnamed: 384', axis=1, inplace=True)
df

,res5.x,res5.y,res5.z,res6.x,res6.y,res6.z,res7.x,res7.y,res7.z,res8.x,...,res129.z,res130.x,res130.y,res130.z,res131.x,res131.y,res131.z,res132.x,res132.y,res132.z
0,-10.821472,-2.033643,-10.725451,-10.721312,-6.334303,-8.265643,-9.548619,-10.406980,-5.356002,-10.473657,...,-19.434105,-5.766649,-14.863527,-13.860638,-14.148989,-18.153286,-11.946570,-14.603769,-10.071678,-10.348105
1,-10.968607,-2.803746,-12.389121,-11.102278,-6.691447,-9.311110,-9.271282,-10.634724,-6.473198,-10.300098,...,-19.560192,-5.116387,-15.562160,-14.524590,-13.867188,-18.979076,-13.721593,-14.304323,-10.710410,-12.115950
2,-11.224972,-3.128738,-12.986448,-11.475349,-7.290015,-9.585707,-10.386653,-11.596939,-7.118436,-10.090001,...,-19.906431,-5.532526,-16.294762,-14.455696,-14.060275,-19.904043,-12.989317,-14.550005,-11.579666,-12.657036
3,-12.264715,-3.377145,-12.400894,-13.040296,-8.110255,-9.782265,-11.838402,-11.344295,-6.201875,-11.268795,...,-19.593458,-5.920282,-16.580149,-13.961607,-13.867020,-20.659210,-12.900354,-15.746778,-12.383794,-11.655579
4,-12.369930,-3.939932,-12.427648,-12.861740,-8.651776,-9.629275,-11.683224,-12.405328,-6.521994,-12.207441,...,-19.087597,-6.286641,-17.603008,-13.539998,-15.430125,-21.237556,-13.819863,-16.893446,-13.017795,-12.313378
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29992,7.383127,7.885204,27.231306,11.317983,6.436976,30.892355,13.710789,3.871247,34.502453,7.037305,...,36.249184,8.482517,-4.809201,33.984074,5.172907,-0.291242,41.586479,6.269903,6.606678,34.671238
29993,8.730219,8.209901,26.840466,10.913787,6.478487,31.880392,13.583369,4.279834,35.367142,7.033583,...,37.066040,8.785833,-4.911178,34.498184,5.716974,0.337568,41.735321,7.020761,6.974929,35.063225
29994,9.183106,7.353646,26.933519,11.374476,6.214723,31.287958,13.729665,3.675851,35.022316,7.310488,...,37.504307,8.765450,-5.536272,34.622955,5.951097,-0.228800,41.899036,5.653042,6.046134,35.187653
29995,8.482318,7.403724,25.823250,11.106685,6.272860,30.374935,14.127182,3.998588,33.821819,7.849520,...,37.076099,9.253329,-5.572351,33.813065,6.374975,-0.017896,40.869068,6.848340,6.318630,34.206329
29996,8.540642,7.165017,25.761999,10.433359,5.730731,30.605051,13.818554,3.733338,33.835346,7.362996,...,36.196606,9.183434,-5.703943,33.837914,5.697646,-0.554307,40.886791,6.985765,6.165180,34.041565

In [5]:
df.to_csv('output_coords_res_merged.csv', encoding='utf-8', index=False)